version: "3.6"

services:
  webapp:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - .:/home/appuser
  db:
    image: 'postgres:12-alpine'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
